### ISSUE TITLE
Example usage with Criterion?

### ISSUE THREAD

**Issue by deklanw** [flamegraph-rs/flamegraph#104]
Trying to piece together how to get this combination working using the docs here and https://bheisler.github.io/criterion.rs/book/user_guide/profiling.html

In my `Cargo.toml`:

```
[[bench]]
name = "my_benchmark"
harness = false
```

Tried this:
`flamegraph target/release/deps/my_benchmark-aab9e5b0e049f722 --bench --profile-time 100`:
```
Gnuplot not found, using plotters backend
Benchmarking apply forces barnes hut/1000: Complete (Analysis Disabled)

[ perf record: Woken up 3139 times to write data ]
[ perf record: Captured and wrote 784.617 MB perf.data (97476 samples) ]
writing flamegraph to "flamegraph.svg"
```

But, when I check the flamegraph it's just two levels
![image](https://user-images.githubusercontent.com/11601778/96922870-74074380-147e-11eb-85aa-66e8ed517f18.png)

I'm a bit lost here. Any help appreciated

**Comment by bjorn3** [comment]
You will need to add the following to `Cargo.toml` I think:

```toml
[profile.bench]
debug = false
```

**Comment by AlexMikhalev** [comment]
Any suggestions how to run above via cargo-flamegraph? 
`cargo bench --manifest-path benches/Cargo.toml --verbose -- --test filters`
but then 
`cargo flamegraph --manifest-path benches/Cargo.toml --bench filter` doesn't lik manifest path and can't find benchmark name filters despite 
```
[[bench]]
name = "filters"
harness = false
path = "src/filters.rs"``
It also complains that Cargo.toml needs 
[profile.bench]
debug = true
which is contradictory to advice above. 
Any good examples of using criterion and flamegraph?

**Comment by djc** [comment]
@AlexMikhalev this seems unrelated, probably better to open a new issue. I think `cargo flamegraph` just doesn't support `--manifest-path`, have you tried going into the `benches` dir and running `cargo flamegraph` from there?

**Comment by AlexMikhalev** [comment]
@djc I am happy to open new issue, I think the titile fits.
Example which worked for me:
Let's start with fresh crate
```
git clone https://github.com/BurntSushi/fst
cd fst/bench
cargo bench 
```
will run criterion benchmarks.
Running `cargo flamegraph` will return 
`Finished release [optimized + debuginfo] target(s) in 0.03s
several possible targets found: ["fst", "test", "build-script-build", "fst"], please pass `--bin <binary>` or `--example <example>` to cargo flamegraph to choose one of them` 
cargo famegraph --bench fst 
will run flamegraph.

**Comment by djc** [comment]
Please open a new issue and document there what works and what you expect to work but doesn't.

**Comment by djc** [comment]
(Going to close this issue, but the original reporter should feel free to reopen if there's still an issue.)

**Comment by AlexMikhalev** [comment]
@djc thank you for good project. All works as above.

**Comment by qiujiangkun** [comment]
FYI, I would use `cargo flamegraph --bench ethernet_interface  --features=unit_bench -- --bench`. The last `--bench` is for criterion to run in benchmark mode, rather than in test mode.

Running tests and benchmarks should also be documented in README.md. @djc

**Comment by djc** [comment]
@qiujiangkun would you be able to submit a PR? Would be much appreciated.
