### ISSUE TITLE
Requirements given in the 'Installation' section of the README don't exist [Debian Sid]

### ISSUE THREAD

**Issue by PatchMixolydic** [flamegraph-rs/flamegraph#106]
The README currently says:
> Requirements on Linux (Ubuntu/Debian):
> `sudo apt install -y linux-tools-common linux-tools-generic`

When attempting to use that command, this happened:
```
→ uname -a
Linux blue-pearl 5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64 GNU/Linux
→ sudo apt install -y linux-tools-common linux-tools-generic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-tools-common
E: Unable to locate package linux-tools-generic
```

Indeed, neither [linux-tools-generic](https://packages.debian.org/search?keywords=linux-tools-generic) nor [linux-tools-common](https://packages.debian.org/search?keywords=linux-tools-common) seem to exist in the Debian package repository. There is, however, an old package named [linux-tools](https://packages.debian.org/stretch/linux-tools), which is a dummy package that installs [linux-perf](https://packages.debian.org/sid/linux-perf), a package which exists to this day. Using this package, I was able to install flamegraph successfully.

**Comment by MTRNord** [comment]
Same issue on debian buster

**Comment by djc** [comment]
Would you mind submitting a PR?
