### ISSUE TITLE
Custom lib_xx.so file via rust-bindings

### ISSUE THREAD

**Issue by bagavi** [flamegraph-rs/flamegraph#108]
I am using a library (created by me) which has an `lib_xxx.so` file in the following location `target/release/build/yyy-xxx-856f3b06a31b6278/out/build`. `cargo run` works as expected however, on running flamegraph, I get the following: `error while loading shared libraries: lib_xxx.so: cannot open shared object file: No such file or directory`. 

I suspect that the perf is not able to find the .so file. Whats the best way to resolve this problem?

Thanks in advance

**Comment by bjorn3** [comment]
You need to add the directory that contains the library to the `LD_LIBRARY_PATH`. Otherwise the dynamic linker doesn't know where to find it. When using `cargo run` this is done for you, but when you directly invoke it, this isn't done automatically. https://github.com/rust-lang/cargo/blob/f03698b3f90f6f4429d38c69e296349079df2b18/src/cargo/core/compiler/compilation.rs#L232-L235

**Comment by djc** [comment]
Are you running flamegraph or cargo flamegraph? I guess it might make sense for cargo flamegraph to also do this.

**Comment by bjorn3** [comment]
`cargo flamegraph` would need to parse output of `cargo build --message-format json` for that I think.

**Comment by bagavi** [comment]
> Are you running flamegraph or cargo flamegraph? I guess it might make sense for cargo flamegraph to also do this.

I am running `cargo flamegraph`

**Comment by bagavi** [comment]
I am using `atlas-ceres` library and hence added the path to its build folder to `LD_LIBRARY_PATH` as below
```
LD_LIBRARY_PATH="/home/vivek/code/atlas/target/release/build/atlas-ceres-c718ad2a8d31c46a/out/build/":${LD_LIBRARY_PATH}
``` 

Also on `ls /home/vivek/code/atlas/target/release/build/atlas-ceres-c718ad2a8d31c46a/out/build/` I get 
`CMakeCache.txt  CMakeFiles  cmake_install.cmake  libatlas_ceres.so  Makefile` as my output

However I still get the following error
`WARNING: Kernel address maps (/proc/{kallsyms,modules}) are restricted,
check /proc/sys/kernel/kptr_restrict and /proc/sys/kernel/perf_event_paranoid.

Samples in kernel functions may not be resolved if a suitable vmlinux
file is not found in the buildid cache or in the vmlinux path.

Samples in kernel modules won't be resolved at all.

If some relocation was applied (e.g. kexec) symbols may be misresolved
even with a suitable vmlinux or kallsyms file.

Couldn't record kernel reference relocation symbol
Symbol resolution may be skewed if relocation was used (e.g. kexec).
Check /proc/kallsyms permission or run as root.
**/home/vivek/code/atlas/target/release/examples/debug_node: error while loading shared libraries: libatlas_ceres.so: cannot open shared object file: No such file or directory**
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.083 MB perf.data (9 samples) ]
failed to sample program
`

**Comment by djc** [comment]
I think we would accept patches that make the environment for `cargo flamegraph` more similar to what `cargo run` sets up, but I probably won't have time to work on this myself unless someone wants to sponsor the work. Happy to mentor and/or review, though!

**Comment by mert-kurttutan** [comment]
I am experiencing the same type of issue. In my case, I binary compiled with dynamic linking to Intel MKL implementation of cblas. 
When I run the binary on its own (i.e. without flamegraph), it runs as  expected since the environment is set by running intel-mkl script. 
But when I do the same for running binary with flamegraph, it gives the same error:
``` 
libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

Also, I am not sure if this issue should actually be closed.

**Comment by mert-kurttutan** [comment]
I get the same error, when I run the perf command as well

**Comment by djc** [comment]
If you get the same error when you run `perf` directly that means the problem is not with the flamegraph tooling -- the flamegraph tooling is merely a thin wrapper over running `perf` and feeding its output to the inferno crate.

**Comment by mert-kurttutan** [comment]
Exactly, I just wanted to make it unknown.
@djc Do you know any solution for this problem ? (This seems to be very generic situation, i.e. using perf on binary with dynamic linking)

I could not find any concrete info on this one on the web.

**Comment by djc** [comment]
Sorry, I don't -- I actually don't have much experience with `perf`.
