### ISSUE TITLE
Function names truncated

### ISSUE THREAD

**Issue by ryanleh** [flamegraph-rs/flamegraph#109]
The function signatures I'm working with are rather long and get truncated in the resulting flamegraph to the point of not being helpful. Is there anyway to make the outputted svg wider to combat this? Thanks!

**Comment by djc** [comment]
There's currently no way to do this as far as I can see. The inferno API (which draws the flamegraph in the end) does [expose options](https://docs.rs/inferno/0.10.2/inferno/flamegraph/struct.Options.html) for this, but flamegraph just [uses the defaults](https://github.com/flamegraph-rs/flamegraph/blob/master/src/lib.rs#L307). If you'd like to contribute some CLI options, that would be great!
