### ISSUE TITLE
lld breaks flamegraph

### ISSUE THREAD

**Issue by sigmaSd** [flamegraph-rs/flamegraph#110]
Hi,
Using lld (llvm linker) instead of the default one makes the graph incorrect, instead of function a calls function b calls function c, I see the the 3 functions on the same row.

I'm light on details because it might be not an issue, maybe lld is not supported?

But reproducing should be simple `env RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo flamegraph`

Tested on linux, flamegraph version 0.4.0

**Comment by djc** [comment]
I don't really use flamegraph on Linux, so reproducing isn't that straightforward for me. Can you show a screenshot of failure case and a correct case?

**Comment by sigmaSd** [comment]
Default linker correct flamegraph:

![20201216_09h22m56s_grim](https://user-images.githubusercontent.com/22427111/102323119-5c30d500-3f80-11eb-8b1b-edc5baf11b99.png)

lld incorrect flamegraph:
![20201216_09h23m13s_grim](https://user-images.githubusercontent.com/22427111/102323175-6fdc3b80-3f80-11eb-85b3-d4e54d8cf8c5.png)

**Comment by djc** [comment]
This doesn't look like a problem with the flamegraph tooling with me, but rather with the underlying executions somehow differing substantially.

**Comment by sigmaSd** [comment]
The two flamegraph I just run with the exact same executions, also I can reproduce with different programs.

Did you try it on windows? maybe its the same issue there?

**Comment by djc** [comment]
My point is, it looks to me like flamegraph here is more or less accurately capturing the underlying data generated by perf, and your problem is deeper down in the stack -- maybe with perf, but that seems not very likely.

**Comment by sigmaSd** [comment]
Ok, I'll just close the issue then for now since there is no obvious solution and the problem might be lower in the stack then flameraph.

If I figure out something I'll post it here, thanks for your time.

**Comment by bjorn3** [comment]
Maybe lld somehow caused the stack usage to increase? You could test by editing the source of `flamegraph` to use `--call-graph dwarf,50000` instead of `--call-graph dwarf` in the `perf record` invocation. This will increase the size of the captured part of the stack.

**Comment by sigmaSd** [comment]
@bjorn3 I tried with `"record -F {} --call-graph dwarf,50000 -g"` but still the same graph
