### ISSUE TITLE
Allow choosing starting point for flamegraph

### ISSUE THREAD

**Issue by kno10** [flamegraph-rs/flamegraph#111]
I've tried to analyze the runtime of an algorithm with cargo flamegraph.
The algorithm of interest is about O(n²) in runtime, so it is worth profiling.
The standard benchmark suite for this problem (ORLib) involves data sets given as networks, that first need to be transformed into a matrix using all-pairs shortest-paths. With Floyd-Warshall this is O(n³). Hence, unsurpisingly, this transformation runtime dominates the flamegraph. An obvious way would be to write out the distance matrix obtained this way and read it back in if necessary in  O(n²). Yet, a more convenient method would be to be able to define the starting point of the flame graph on the command line (and this way, ignore the loading function). E.e., `cargo flamegraph --starting-point mycargo::starting_point`.

**Comment by kno10** [comment]
I tried writing the square matrix to a file and reading it back. Now IO dominates the flame graph, and it still does not allow me to see much of the method of interest. Such a starting point visualization may be nice to have. But OTOH, the runtime of the remainder is so small, I cannot see anything in perf either; I would probably need to use even larger problems for benchmarking.

**Comment by michaelkirk** [comment]
Just in case you weren't already aware, you can "zoom in" to a flame graph portion by clicking on the stack frame, at least when viewing the SVG in a browser.

If that's not sufficient, can you elaborate on why not?

**Comment by kno10** [comment]
Thanks. I didn't know that.
I had opened the svg in inkscape.
