### ISSUE TITLE
Support cargo `--no-default-features`

### ISSUE THREAD

**Issue by ashpil** [flamegraph-rs/flamegraph#114]
Currently, flamegraph supports the `--features` cargo flag, however, I don't think there's any way to work with that and disable default features. It would be nice if you could disable default features when running flamegraph (and this would be extraordinarily simple to implement). 

It might be even better to have some sort of cargo passthrough, where one can specify a `--cargo-cmd="--no-default-features"` or something that would pass any given command to cargo.

**Comment by djc** [comment]
If you implement it, I'll review it. I think I'd prefer to stick to just `--no-default-features` for now, rather than a passthrough option.

**Comment by ashpil** [comment]
See #115.
