### ISSUE TITLE
Bigger flames 🔥 !

### ISSUE THREAD

**Issue by bestouff** [flamegraph-rs/flamegraph#119]
When running code with many "parallel" functions deep in the call stack, often the function names are cut leaving only their prefix (or even some empty space when the flame is very small).
Could there be an option to have a "wider" flamegraph ? So that those with big screens can enjoy reading all function names, or even those with small screens if they accept to scroll the svg.

**Comment by djc** [comment]
Yes: https://github.com/flamegraph-rs/flamegraph/pull/118. 👍

**Comment by bestouff** [comment]
Ooh great, thanks !

**Comment by bestouff** [comment]
Duplicate of #109
