### ISSUE TITLE
False `building without debuginfo` warning when running benchmarks

### ISSUE THREAD

**Issue by eugene-babichenko** [flamegraph-rs/flamegraph#123]
When running benchmarks there is always a false `building without debuginfo` even when they are certainly enabled and reflected in a flamegraph. This must not happen since this is very misleading.

This is most likely due to [this condition](https://github.com/flamegraph-rs/flamegraph/blob/master/src/bin/cargo-flamegraph.rs#L199-L202) that expects all binaries names to end with a target name. In practice, benchmark binaries names are in format `bench-deadbeef` like intermediate build artifacts.

**Comment by djc** [comment]
A fix for this would be great! Could you contribute something toward this goal?

**Comment by eugene-babichenko** [comment]
I plan to work on it when I have time. This is not really critical and I put it here in hope somebody may pick it up :)
