### ISSUE TITLE
Show line number in the flamegraph

### ISSUE THREAD

**Issue by qiujiangkun** [flamegraph-rs/flamegraph#130]
Can I make it show more information like line numbers in the flamegraph? Sometimes there are too generic functions like Into::into(), making it hard to find in code. Line numbers will help a lot.

There are already line numbers in debug_info as I can see them in gdb. How can I do it?

**Comment by djc** [comment]
I think this question might make more sense in the inferno repository -- as I understand it, inferno is the part that turns call stack files into pretty pictures.
