### ISSUE TITLE
Fails to locate "integration" tests

### ISSUE THREAD

**Issue by bjchambers** [flamegraph-rs/flamegraph#132]
https://github.com/flamegraph-rs/flamegraph/blob/master/src/bin/cargo-flamegraph.rs#L321

When I run a simple example, it seems like the tests show up in `target/debug/deps` instead of `target/debug`.

As far as I can tell:

* `target/debug/<package>` is used for the collected tests within the `src` folder.
* `target/debug/deps/<file>` is used for `file.rs` in the `tests` folder.

If you have "integration" tests (in `tests` instead of `src`) you can't use `cargo flamegraph` to run them.

It looks for benchmarks the `deps` directory is added, but for tests, it seems like it may be a bit tricky since the directory seems to depend on the kind of test.

**Comment by djc** [comment]
Maybe we could try both paths for tests and see which one exists? Should probably try the current approach first to make it more compatible for existing users. If you want to attempt a PR, that would be great!
