### ISSUE TITLE
How to know line number? (seems only see functions in frame graph)

### ISSUE THREAD

**Issue by fzyzcjy** [flamegraph-rs/flamegraph#163]
Hi thanks for the lib! I want to know that, inside a function, what is the portion of time execution for each line of code. How can I do this? Thanks!

**Comment by petar-dambovaliev** [comment]
> I don't think this information is available in the flamegraph tooling in general.

i struggle to understand how flamegraphs are useful, in that case.
It's like...ok, something somewhere in this function is taking a lot of time.
It is just useful enough not to be completely useless.
