### ISSUE TITLE
dtrace: failed to execute / Permission denied on MacOS

### ISSUE THREAD

**Issue by ionionascu** [flamegraph-rs/flamegraph#164]
After reading an article about using criterion.rs and cargo flamegraph (v0.4.0), I wanted to test it on my MacOS (11.6.1) for a project I am working on and I got the below error (I got it for both rust 1.56 and 1.56.1):

```
sudo cargo flamegraph --root --bench lambda -o lambda-baseline.svg -v --dev -- --bench

[...]
Finished dev [unoptimized + debuginfo] target(s) in 51.15s

workload: ["/Users/[...]/target/debug/deps/lambda-9077372e8a07431b.5a7xaodij9y5bos4.rcgu.o", "--bench"]
command "sudo" "dtrace" "-x" "ustackframes=100" "-n" "profile-997 /pid == $target/ { @[ustack(100)] = count(); }" "-o" "cargo-flamegraph.stacks" "-c" "/Users/[...]/target/debug/deps/lambda-9077372e8a07431b.5a7xaodij9y5bos4.rcgu.o --bench"
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute /Users/[...]/target/debug/deps/lambda-9077372e8a07431b.5a7xaodij9y5bos4.rcgu.o: Permission denied
failed to sample program
```

In `Cargo.toml` I have the following settings:

```
[package]
[...]
edition = "2021"

[...]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.bench]
debug = true

[dev-dependencies]
[...]
criterion = { version = "0.3.5", features = ["async_tokio", "html_reports"] }

[[bench]]
name = "lambda"
harness = false
```

(I used `[...]` to hide personal details)

The file `target/debug/deps/lambda-9077372e8a07431b.5a7xaodij9y5bos4.rcgu.o` is not executable. If I use `chmod +x` on it, then the error reported by dtrace changes to:
```
dtrace: failed to execute /Users/[...]/target/debug/deps/lambda-9077372e8a07431b.5a7xaodij9y5bos4.rcgu.o: (os/kern) failure
failed to sample program
```

I get a similar error when running without `--dev`. Benchmarking with `cargo bench` works just fine. SIP is enabled, but I am not sure it should cause any problems like this.

I do not know whether the error I get qualifies as an issue for this project, but I do not think I am doing something wrong.

**Comment by ede1998** [comment]
It looks like `cargo flamegraph` finds the wrong file to execute. 
#141 should fix that but I'm not sure if it's been released yet.

You could try installing the `cargo flamegraph` from the repository directly. 
```
git clone https://github.com/flamegraph-rs/flamegraph.git
cd flamegraph
cargo install --path .
```
That should do the trick.

**Comment by ionionascu** [comment]
@ede1998 , thank you for your reply. Using the code on the master works just fine. I will close this issue.
