### ISSUE TITLE
Error in generated SVG: invalid Char value 27 (<0x1b>) (macOS)

### ISSUE THREAD

**Issue by filippo-orru** [flamegraph-rs/flamegraph#166]
The generated svg cannot be opened. Firefox refuses to load the svg at all while Chrome shows this:
> This page contains the following errors:
> error on line 414 at column 105864: PCDATA invalid Char value 27
> Below is a rendering of the page up to the first error.

The problem is the char `<0x1b>` at the specified location in the file:
<img width="79" alt="<0x1b>" src="https://user-images.githubusercontent.com/33554869/139840309-cc9f0a23-c257-4141-b8fa-2a7062f2a8a5.png">

When I delete it from the file, it loads without errors.

**Comment by djc** [comment]
What OS are you on? I'm guessing this might be part of the perf or dtrace data.

**Comment by ffactory-ofcl** [comment]
I'm on macOS (as stated in the title).

**Comment by djc** [comment]
@jonhoo have you seen anything like this before? Seems like this might make more sense as an inferno issue?

**Comment by ffactory-ofcl** [comment]
Happy to help if you have more questions. The project I benchmarked is https://github.com/ffactory-ofcl/fourinarow-server in case you want to try.

**Comment by jonhoo** [comment]
Huh, no, haven't seen anything like it. It does suggest that there's a weird Unicode code point in a function name or something.  The fact that you _get_ a SVG suggests that Inferno is handling the code point just fine, but it needs to be escaped somehow in the output. It'd be helpful to know some more context here, like where this code point appears in the SVG, and what value it's a part of.

**Comment by ffactory-ofcl** [comment]
The context would be my project, which I linked above. You can try building and running it for a few seconds, it'll most probably contain the code point - that is if the bug comes from my project and not from running on mac.

Sidenote @jonhoo: big fan of your videos :)

**Comment by jonhoo** [comment]
Ah, sorry, what I meant was context in the sense of the surrounding context of the indicated file. That is, can you copy-paste the surrounding lines of the SVG, as well as (if you can) the lines of the generated trace file that's fed _into_ inferno that contain the problematic code point?

**Comment by mosure** [comment]
![flamegraph](https://user-images.githubusercontent.com/35904762/222652584-5effb135-45dc-4e56-a884-412e6a4d302b.svg)

I am able to reproduce when using VSCode `ritwickdey.LiveServer` extension to serve the above SVG.

**Comment by yanns** [comment]
I'm having the same issue, on macos as well.

**Comment by djc** [comment]
See earlier comments from @jonhoo.

**Comment by yanns** [comment]
I've created https://github.com/jonhoo/inferno/issues/313 to track this issue upstream.
