### ISSUE TITLE
Support custom cargo profiles

### ISSUE THREAD

**Issue by frankier** [flamegraph-rs/flamegraph#167]
Now that https://github.com/rust-lang/cargo/issues/6988 is stabilized, it might be nice if it were possible to specify any profile rather than just --dev or --release. This was we can have an optimised debug release which is probably optimal for flamegraphing:

```
[profile.release-debug]
lto = "fat"
codegen-units = 1
debug = true
```

**Comment by djc** [comment]
Would be happy to have a PR for this, though I'd probably want to hold off merging until `--profile` is actually available in stable.

**Comment by tranzystorek-io** [comment]
> Would be happy to have a PR for this, though I'd probably want to hold off merging until `--profile` is actually available in stable.

The time has come! 🥳 

I wonder if there is a way for `flamegraph` to provide a default "inherit from release + debug_symbols" profile?
