### ISSUE TITLE
`--manifest-path` doesn't seem to work (or behaviour does not match usual semantics)

### ISSUE THREAD

**Issue by masklinn** [flamegraph-rs/flamegraph#168]
Normally `--manifest-path` allows cargo-ing within a specific project from an unrelated location e.g. `cargo run --manifest-path ~/some/project/Cargo.toml` will run `~/some/project` but with the current `PWD`, which is useful for testing CLI utilities which work on `PWD` (e.g. because an override seems unnecessary or hasn't been built yet).

Doing that with flamegraph, however, yields the following:
```
Error: failed to access crate metadata

Caused by:
    `cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/current/working/directory` or any parent directory
```

**Comment by masklinn** [comment]
Note: `cargo metadata --manifest-path ~/some/project/Cargo.toml` works just fine.

Looking at #121 it might be that `--manifest-path` is forwarded to `cargo build`, but not provided to `metadata_cmd`, so building will use the correct crate but getting the metadata won't.

Apparently getting the metadata right is not critical (I have not looked how they're used) but it seems to mean `flamegraph` can only be invoked from a directory which contains a `Cargo.toml` (directly or in one of its parents).

`workload` probably needs to [pass `manifest-path` through](https://docs.rs/cargo_metadata/0.14.1/cargo_metadata/struct.MetadataCommand.html#method.manifest_path).

**Comment by djc** [comment]
@ede1998 is this something you would like to contribute? It seems straightforward and you know the surrounding code.

**Comment by masklinn** [comment]
I'm back home so I can probably create a PR for it tomorrow (assuming it's just `workload` which needs to be updated) and I assume ede1998 can review it or something, or can  take a gander and see if there are other bits which need updating.

**Comment by djc** [comment]
@masklinn that would be great, too, thanks! In any case, it definitely makes sense to me to add this.

**Comment by ede1998** [comment]
That seems like something I missed when implementing #141.
Thanks for catching it. I wasn't aware what the option does so I forgot to send it to `metadata`.

The changes should be limited to just the `cargo-flamegraph.rs` file. Not sure which methods would be affected from the top of my head though.
I can review it of course (or implement it but as you already offered to do it, I'll leave it to you.)
