### ISSUE TITLE
allow customization of CollapseOptions

### ISSUE THREAD

**Issue by romange** [flamegraph-rs/flamegraph#171]
inferno's `CollapseOptions` have some useful tunings. It could be nice if we could customize those via flamegraph. 
See https://github.com/flamegraph-rs/flamegraph/blob/main/src/lib.rs#L271  where they are instantiated.

1. Would you agree to this enhancement?
2. How would you suggest to propagate them? One way is to explicitly declare each option and manually propagate them, 
but I thought it could be nice to do something like `--collapse_options=key1=val1,key2=val2...` and let the underlying struct deserialize those key pairs. This approach would reduce the maintenance overhead and give 100% coverage of these options.

**Comment by djc** [comment]
Sounds good to me. Your approach sounds good too, though I'd just name the option `--collapse`.

**Comment by romange** [comment]
sure. I just noticed that collapse options do not derive from `Deserialize`. 
Do I have to add `Deserialize` trait  inside inferno lib or I can somehow add this trait externally inside flamegraph?

**Comment by djc** [comment]
Would be easier to add upstream. They're usually fairly responsive.

**Comment by romange** [comment]
@djc   After learning about it more I understood that in order to use serde I would need to implement my own deserializer that will  parse key-value list. Sounds like an overkill. So, I will probably go with the simplest option of explicitly exposing a subset of collapse options unless you know a crate that allows deserializing structs in such format.

**Comment by djc** [comment]
I think https://docs.rs/serde_urlencoded/0.7.0/serde_urlencoded/index.html could do the job, but might be overkill. Maybe just doing manual (per-platform) implementations is the right thing here. I suppose the upstream `collapse::Options` aren't likely to see a lot of change anyway.

**Comment by romange** [comment]
Will something like this https://github.com/romange/flamegraph/commit/aadca80574bc143d40e1e8c52a8843f483bda283  
be ok? I still need to add a stub function for no-linux os.

**Comment by djc** [comment]
Yes, please submit a PR.
