### ISSUE TITLE
main function only takes about 80% of the whole time

### ISSUE THREAD

**Issue by dclong** [flamegraph-rs/flamegraph#175]
I used flamegraph to profile my application. The main function of the applications takes only about 80% of the whole time. Is the time spent out of the main function used by flamegraph itself or is this a bug? 

![ksnip_20211123-235840](https://user-images.githubusercontent.com/824507/143197816-6273a13d-2d04-457b-926b-f51765a1ef71.png)

**Comment by dclong** [comment]
If this is not a bug, can I just scale everything (with respect to the percentage of the main function) to get the real percentage of time that each part of code consumes?

**Comment by djc** [comment]
This is really more of a function of the perf (on Linux) or dtrace (on macOS or Windows) tooling to create the call stacks, so I think you should investigate on that side. The flamegraph tool is really just a tool to convert perf/dtrace output into flamegraphs using the inferno library.

**Comment by dclong** [comment]
So I guess I can just divide the the percentage that each function uses by 80% (the percentage of time used by the main function) to get the real percentage of time that each function would consume?

**Comment by djc** [comment]
Sure. In general, I think flamegraphs are mostly used to get a sense of where time is spent relative to other functionality. Presumably if 80% of the time is spent outside main, that's not a particularly heavy workload. (Or alternatively, your project spends substantial time initializing static variables.)

**Comment by dclong** [comment]
Thank you so much for the help!
