### ISSUE TITLE
linux-perf does not seem to exist on Ubuntu

### ISSUE THREAD

**Issue by smu160** [flamegraph-rs/flamegraph#176]
Hi,

I attempted to install the prerequisite using the provided instructions, but I got the following error on Ubuntu 21.10 (5.13.0-21-generic).

```bash
$ sudo apt install -y linux-perf
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-perf
```

The fix for me was:

```bash
$ sudo apt-get install linux-tools-common linux-tools-generic linux-tools-`uname -r`
```

This instruction seems to have changed [before](https://github.com/flamegraph-rs/flamegraph/pull/133).

Thank you!

**Comment by djc** [comment]
Well, okay, if someone can provide a comprehensive description of how to install perf on different distributions, I'd be happy to review a PR.

**Comment by djc** [comment]
We now have better instructions in the README, closing this for now.
