### ISSUE TITLE
cargo flamegraph unable to generate a flamegraph from the collapsed stack data

### ISSUE THREAD

**Issue by Nevsden** [flamegraph-rs/flamegraph#181]
So I am running the `cargo flamegraph` command together with the example flag. 
The curious thing is, sometimes the command works completely but most often, I get this error message:

```txt
[ perf record: Woken up 322 times to write data ]
[ perf record: Captured and wrote 84.717 MB perf.data (10528 samples) ]
writing flamegraph to "flamegraph.svg"
Error: unable to generate a flamegraph from the collapsed stack data

Caused by:
    0: I/O error: No stack counts found
    1: No stack counts found
```

Diving into the code, the responsible part on the `flamegraph` side seems to be [this code](https://github.com/flamegraph-rs/flamegraph/blob/648c9cebfc1ad3c543f1eca89db34a7f76708310/src/lib.rs#L319):

```rust
 let mut inferno_opts = opts.flamegraph_options.into_inferno();
    from_reader(&mut inferno_opts, collapsed_reader, flamegraph_writer)
        .context("unable to generate a flamegraph from the collapsed stack data")?;
```

On the `inferno` side it seems as if the time accumulated from the stack trace is zero. At this point I am unfortunately not yet familiar enough to know, how to fix the problem myself. 

Maybe this is an issue for the inferno crate?

**Comment by djc** [comment]
Yes, I think this would better be reported to the inferno repository.

**Comment by Nevsden** [comment]
Thank you for your fast reply!
