### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by nilgoyette** [flamegraph-rs/flamegraph#193]
Maybe this is more of a question than an issue. I calculated the flamegraph of a binary with `debug = true` and a single core. The results are divided in a way that doesn't make sense to me. I know that `Topop::run` is only called once by main, but I see it in five columns (see purple lines in image). By the way, I can't legally share the code; it belongs to a private enterprise.

![Columns](https://user-images.githubusercontent.com/2658640/156805854-bf1fb84d-2e5e-41c9-8d99-a915c33c5aef.png)

I would have thought that `Topop::run` would be a single long row taking 98.5% of the width. Do you know why this happens? Should I disable or enable something?

Moreover, I calculated the graph for the same binary with `debug = false`. Both graphs look alike but there are some huge differences. For example, I search for a specific function and I obtain wildly different sums: 45.6% (true) and 11.1% (false). The `debug = false` version seems to make more sense. In general, which `debug = ?` should we believe when they disagree?

**Comment by mstange** [comment]
`debug = true` is the one that you should believe more. Without debug information, you lose information about any functions which were inlined by the compiler.
In your example, it looks like stack unwinding failed to get the immediate parent function of `Topup::run` or of `main` most of the time. The spot where `Topup::run` is the "deepest" is actually the correct one, I think. In the other calls, I think those same parent frames were on the stack, but they were lost inside the `[unknown]` frame.

Another thing you can try is to compile with `RUSTFLAGS="-C force-frame-pointers=yes" cargo build [...]` and see if that gives you more consistent stacks.

**Comment by djc** [comment]
flamegraph (and cargo flamegraph) is basically glue code between perf/dtrace and inferno. If you get garbage in from perf, you're going to get garbage out; but there's not much I can do in flamegraph, as far as I can tell.

**Comment by mstange** [comment]
> I had no success with the "frame pointer" trick, with or without debug information.

Ah, that's too bad, thanks for trying.

**Comment by mstange** [comment]
After looking into this more, I think the truncated stacks occurred because perf wasn't copying enough stack memory into the perf.data file. By default it copies 8192 bytes. We can increase the limit by passing a higher number here:

https://github.com/flamegraph-rs/flamegraph/blob/eb17b4829558ed1e57e3cc9df586fda40f328a62/src/lib.rs#L59

Instead of `--call-graph dwarf` we could specify `--call-graph dwarf,16384` .

**Comment by mstange** [comment]
The easiest workaround for users would be to run `flamegraph` with `--cmd "record -F 997 --call-graph dwarf,16384 -g"` .

**Comment by djc** [comment]
Should we do that by default?

**Comment by mstange** [comment]
I think that's worth doing, yes. It'll lead to larger perf.data files, but if the results are less confusing, it's probably worth it.

Here are three flame graphs I collected on [dump_syms](https://github.com/mozilla/dump_syms/) with varying stack sizes:

 - [8192 bytes, 137MB perf.data](https://mstange.github.io/tmp/flamegraph-8192-137MB.svg): Only 5% of stacks made it all the way to `_start`, the rest is broken and grouped under `[unknown]`.
 - [16384 bytes, 269MB perf.data](https://mstange.github.io/tmp/flamegraph-16384-269MB.svg): 71% of stacks are good
 - [32768 bytes, 559MB perf.data](https://mstange.github.io/tmp/flamegraph-32768-559MB.svg): Marginally better, a few high towers have moved into the good part.

The remaining broken stacks seem to be broken for a different reason which I haven't investigated yet.

**Comment by djc** [comment]
Would you mind submitting a PR for that?

**Comment by mstange** [comment]
Submitted #201.

**Comment by mstange** [comment]
> The remaining broken stacks seem to be broken for a different reason which I haven't investigated yet.

It turns out they are broken for the same reason. For example, the 20% samples in `read_cfi` have their stacks truncated in that function because it function puts a 47KB value on the stack.
https://github.com/getsentry/symbolic/blob/9e04315b54f1dd38e2f483eabbf1857abaf44041/symbolic-minidump/src/cfi.rs#L580

**Comment by nilgoyette** [comment]
I tested this again using `--cmd "record -F 997 --call-graph dwarf,16384 -g"` and the results are much better! I get the following warning

    Warning:
    Processed 924767 events and lost 7 chunks!

    Check IO/CPU overload!

but at least I don't have the full-width `unknown` line. There are still several `unknown`  blocks but they are tiny and easy to ignore because they are at the top of the "flames". I guess I could remove them by using a bigger number than 16384 but I'm already losing some chunks :) Anyway, the flamegraph is usable now, yeah!

Thank you @mstange for investigating.

**Comment by mstange** [comment]
Excellent! Thanks for reporting back.

**Comment by davidhalter** [comment]
@djc I think it would be valuable to mention the limitation of the stack size. I have tried a lot of different things and increasing the size like `flamegraph -c 'record --call-graph dwarf,50000 -g'` helped a lot. Before I would only get about 20% proper stacks (a lot of "[Unknown]"). This might only apply to me, but I personally doubt it. It might also be interesting to make that value configurable.

**Comment by djc** [comment]
@davidhalter this crate is only getting passive maintenance -- happy to review a PR in that direction, though!
