### ISSUE TITLE
DTrace cannot instrument translated processes

### ISSUE THREAD

**Issue by guanguoliang** [flamegraph-rs/flamegraph#219]
My os is: macOs Monterey 12.2.1, cargo-flamegraph 0.6.2, when I exec "cargo flamegraph --root", it show an error msg like "dtrace: failed to execute /Users/guoliang/code/hello-rust/target/release/hello-rust: DTrace cannot instrument translated processes", and I tried to build with "x86_64-unknown-linux-musl", it  also showed the same  msg.I don't know what I can do to resolve it

**Comment by mstange** [comment]
"Translated processes" usually means you're running an x86_64 process on an Apple Silicon machine (under Rosetta).

For Apple Silicon machines, the correct native target triplet is `aarch64-apple-darwin`. You may by using an x86_64 Rust compiler, or you may have manually configured your Rust build to create `x86_64-apple-darwin` builds. Make sure `rustup show` says "Default host: aarch64-apple-darwin". If it says "Default host: x86_64-apple-darwin" instead, try installing rustup from scratch from [rustup.rs](https://rustup.rs/).

**Comment by guanguoliang** [comment]
thanks, I moved all config from old mac to new one, no wonder it compiled wrong
