### ISSUE TITLE
flameCHART keeps generating flameGRAPH.svg

### ISSUE THREAD

**Issue by brainstorm** [flamegraph-rs/flamegraph#247]
When the `--flamechart` option is given, the default `-o` should be `flamechart.svg` instead of `flamegraph.svg`?

Similarly, the title of the chart/graph should change accordingly to avoid confusion and overwriting flamegraphs with flamecharts accidentally. For instance, the following image was generated as a `--flamechart`, but the title reads `Flame Graph`:

![Screenshot 2023-01-16 at 4 47 24 pm](https://user-images.githubusercontent.com/175587/212607099-7e7dedd7-1b0b-45c3-83c2-75cf5dce1a08.png)

... generated from https://github.com/umccr/htsget-rs/pull/137/files#diff-737fb5e48b4dcf12a9d9e04bc36ff2f3bce43cf1ee94a626142e5c3f83fea6a8R55-R58

**Comment by djc** [comment]
I think the output file name refers to the name of the tool, not the style of chart, so I think changing it would be confusing more than helpful. If you want to submit a PR to change the title, I'd be happy to review it.

**Comment by brainstorm** [comment]
I find your proposal even more confusing: changing the title is ok but not the filename? Very inconsistent, so I think I'll just leave it as is an perhaps contribute something more substantial than a 2 word change pullrequest X"D

Other than that, very nice crate, btw, thanks!
