### ISSUE TITLE
It does not work as expected, no Rust function names!

### ISSUE THREAD

**Issue by cmarincia** [flamegraph-rs/flamegraph#254]
Hello!
I am on Solus Linux 4.3.
```
$ uname -a
Linux catalin 6.1.5-229.current #1 SMP PREEMPT_DYNAMIC Thu Jan 12 20:29:03 UTC 2023 x86_64 GNU/Linux
```

```
$ rustup default
stable-x86_64-unknown-linux-gnu (default)
```
```
$ rustup --version
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.67.1 (d5a82bbd2 2023-02-07)`
```
```
$ cat ~/.cargo/config.toml

[build]
rustc-wrapper = "/home/catalin/.cargo/bin/sccache"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

Cargo.toml file:
```toml
[package]
name = "flametest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
debug = true
```

main.rs
```rs
use std::collections::HashMap;

fn hello() {
    println!("hehe");
}

fn main() {
    let mut h = HashMap::new();
    let mut v = vec![];
    for i in 0..100 {
        hello();
        v.push(i);
    }
    for i in v {
        h.insert(i, i);
        print!("{}", h.get(&i).unwrap());
    }
}
```
I did tried with both
```
echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
```
and
```
echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid
```

Used the following commands:
```
sudo -E /home/catalin/.cargo/bin/cargo flamegraph --open --dev
```
```
sudo -E /home/catalin/.cargo/bin/cargo flamegraph --open --dev --root
```
```
cargo flamegraph
```

![flamegraph](https://user-images.githubusercontent.com/35623921/220760061-d1deb206-ddec-4bf3-a86d-e5059e0db9d9.svg)

I expected to have at least some basic method calls for the hashmap. Nothing very useful there.
What am I doing wrong?

**Comment by mstange** [comment]
Your program might be running for a very short time. Try upping the number of iterations.

**Comment by cmarincia** [comment]
It seems that did the trick, why is that happening? Is it possible to configure perf to get even the current amount of iterations?

**Comment by mstange** [comment]
perf samples your program at a certain interval, for example every 1ms. If your program is so fast that it falls between the sampling times, then you won't get any stacks. This is a problem that's common to all sampling profilers.

**Comment by cmarincia** [comment]
I found out that specifying a bigger frequency is actually producing very good results in the resulted flamegraph:
```
cargo flamegraph -F 10000
```
The default frequency is 997: https://github.com/flamegraph-rs/flamegraph/blob/main/src/lib.rs#L57
also: https://baptiste-wicht.com/posts/2011/07/profile-applications-linux-perf-tools.html
