### ISSUE TITLE
Proposed feature: filter/match

### ISSUE THREAD

**Issue by jedbrown** [flamegraph-rs/flamegraph#259]
Brendan Gregg's [instructions for the perl tools](https://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html#Instructions) has lots of examples that use `grep` to prune the folded traces. This Rust implementation is nicer in many ways, but I often find myself missing this feature (mostly when working with `--perfdata perf.data`) and relearning some conventions of the perl implementation.

I can imagine this being addad a regex to match or by passing a representation through an external filter (likely ripgrep) or by having an option to emit output similar to `stackcollapse-perf.pl` with another to read it (usually from stdin) so the user can construct such pipelines. I wonder if the maintainers have thought about how this should be implemented.

**Comment by djc** [comment]
`flamegraph` is a fairly thin wrapper around the inferno crate, which already has some support for various [options](https://docs.rs/inferno/latest/inferno/collapse/perf/struct.Options.html). However, not all of those options are currently exposed through the `flamegraph` CLI. If you want to submit a PR to improve on that, I'd be happy to review! Have a look at the [`FlamegraphOptions`](https://github.com/flamegraph-rs/flamegraph/blob/main/src/lib.rs#L493) and the [conversion](https://github.com/flamegraph-rs/flamegraph/blob/main/src/lib.rs#L493) to inferno options.

**Comment by jedbrown** [comment]
I'm ashamed to say I didn't notice that #216 provides this feature as an external filter. There's a related feature I'd like, which is to process stacks as input, but I can hack it this way and I see where to add the feature properly.
```console
$ flamegraph --post-process 'cat my-stacks.txt' -- /bin/true
```
