### ISSUE TITLE
Attach to an already open process

### ISSUE THREAD

**Issue by HKalbasi** [flamegraph-rs/flamegraph#266]
In order to prevent XY problem, here is what I want to do: I want to generate a flamegraph for rust-analzyer, while it is being used in an editor (I can't write a unit test similar enough to the real world workload). I can't start the r-a process by flamegraph since at the start it put some time on caching some things which I'm not interested in. I want to open r-a, wait for it to finish it's caching, then attach to it with flamegraph, then do the thing that I want to optimize in the editor, wait for it to finish, and then close the flamegraph and see the generated file. Is it possible in this tool or other similar tools to do that?

**Comment by djc** [comment]
```
djc-2021 migrate-video epoxide $ flamegraph -h
flamegraph 0.5.1

USAGE:
    flamegraph [FLAGS] [OPTIONS] [trailing-arguments]...

FLAGS:
    ..

OPTIONS:
    ..
    -p, --pid <pid>                    Profile a running process by pid
```

?

**Comment by HKalbasi** [comment]
Thanks! Sorry for noise.
