### ISSUE TITLE
The call stack of functions mostly records addresses

### ISSUE THREAD

**Issue by CrazyboyQCD** [flamegraph-rs/flamegraph#277]
OS: Windows 10
![259365209-02a84cd6-ce43-4545-8502-c802c0d1f132](https://github.com/flamegraph-rs/flamegraph/assets/53971641/49393894-b758-474d-9eb0-c0645872f344)
I had the same output as example before, but after a while, I got the "No stacks count" error. Then I took several administrative operations about permissions and found out that I need to disable Windows Defender. And now I have no idea why Dtrace for windows can't initiate, I have to use blondie as an alternative.

**Comment by djc** [comment]
So using blondie works well? That seems like a good solution?

**Comment by CrazyboyQCD** [comment]
> So using blondie works well? That seems like a good solution?

it works and dtrace also does the good job if I figure out what I've done to my windows that broke it
