### ISSUE TITLE
Function names encapsulated by other characters

### ISSUE THREAD

**Issue by arctic-alpaca** [flamegraph-rs/flamegraph#280]
Hi, 

the function names in generated flamegraphs have become encapsulated by other characters. Please see the attached screenshot for details:
![grafik](https://github.com/flamegraph-rs/flamegraph/assets/67190338/9421b7b1-1816-47c6-8409-0ce71eabd91d)

This started happening after using version 0.6.2 without issue for some time and updating to 0.6.3 did not change the behavior. 

I'm guessing this is triggered by my environment as flamegraph was not updated at the time the issue appeared but I don't know what could be causing this.

Command used:
`cargo flamegraph --bench ipv6 -- --bench --profile-time 10`

Profile:
```
[profile.bench]
debug = true
```

Rust version: rustc 1.74.0-nightly (5c6a7e71c 2023-08-20)

**Comment by djc** [comment]
What platform are you using flamegraph on? How is the code that you're profiling generated?

**Comment by arctic-alpaca** [comment]
I'm using Fedora 38 (`uname -r ` prints `6.4.11-200.fc38.x86_64`) on x86_64.

>  How is the code that you're profiling generated?

I'm not entirely sure what you mean by this. I'm using criterion with code I wrote and successfully generated flamegraphs with properly displayed function names for before.
The behavior shown in the sceenshot also appears when using flamegraph on an example in my project (`cargo flamegraph --example my_example --root`).
I tried multiple old projects to see if there was any difference but they all show the unwanted characters.

**Comment by arctic-alpaca** [comment]
I tracked the problem down to an issue with the installed perf version. After downgrading from perf-6.4.4-200.fc38 to perf-6.2.6-300.fc38, Rust symbols are demangled properly again. Sorry for the noise here.

**Comment by djc** [comment]
No problem, glad you figured it out!

**Comment by DevJac** [comment]
I'm having the problem on Fedora as well. It appears the latest versions of perf do not demangle the names correctly?

**Comment by djc** [comment]
Would be great if someone can look for/file a bug against Fedora and reference it here.

**Comment by arctic-alpaca** [comment]
I did file an [issue](https://bugzilla.redhat.com/show_bug.cgi?id=2233269) in the RedHat bugtracker as this is where the "File a new bug report" link on the [fedora package site](https://packages.fedoraproject.org/pkgs/kernel-tools/perf/) leads to.

**Comment by djc** [comment]
@arctic-alpaca awesome, thanks!

**Comment by kangalio** [comment]
On Fedora 39, the oldest available perf package is 6.5.4 (and the newest is 6.6.3), which still have the bug :( Will update if I find a workaround

**Comment by Omar-Elrefaei** [comment]
To install required dependencies to build `perf` with most optional features enabled.
`dnf install elfutils-devel libdwarf libdwarf-devel libcap-devel elfutils-libelf-devel numactl-libs libunwind-devel lzma-sdk-devel libaio-devel libtraceevent-devel libfm-devel slang-devel systemtap-sdt-devel perl-devel binutils-devel libbabeltrace-devel` 

then you can run `dnf mark remove {package_names}...` in order to label them as "autoinstalled" if you want them to be removed later.
