### ISSUE TITLE
Name mangling in output

### ISSUE THREAD

**Issue by blp** [flamegraph-rs/flamegraph#283]
When I run `cargo flamegraph`, I see mangled names in the output. I see that there are mangled names in the sample flamegraph at https://github.com/flamegraph-rs/flamegraph, too. Mangled names are hard to read.

To get them demangled, I had to put the following script as `addr2line` early in my path:

```
#! /bin/sh
/usr/bin/addr2line "$@" | rustfilt
```

I'm surprised that this isn't something that anyone has noticed or filed or fixed before? I do wonder if I'm missing something.

Thanks,

Ben.

**Comment by djc** [comment]
There seems to be a recent regression in perf going around? Have a look at #280.

**Comment by blp** [comment]
> There seems to be a recent regression in perf going around -- are you on Fedora? Have a look at #280.

Oh, yeah, this duplicates #280. I looked but couldn't find a dup before I filed, sorry about the noise.

I am also on Fedora.
