### ISSUE TITLE
Run on WSL has only 1 sample in the flamegraph

### ISSUE THREAD

**Issue by albertsgarde** [flamegraph-rs/flamegraph#288]
I can succesfully run `cargo flamegraph` in WSL, but the resulting flamegraph looks like the image below and hovering over the functions shows that each only has 1 sample.
This is inconsistent with the output to the terminal which is
```
albert@LAPTOP-P9O7TTBR:~/evolution$ cargo flamegraph --bin benchmark
    Finished release [optimized + debuginfo] target(s) in 0.27s
Ticks per second: 1065772.6
[ perf record: Woken up 316 times to write data ]
[ perf record: Captured and wrote 79.191 MB perf.data (4992 samples) ]
writing flamegraph to "flamegraph.svg"
```
(the `Ticks per second` is just output from the program)
![flamegraph](https://github.com/flamegraph-rs/flamegraph/assets/20074572/11ff2807-5134-4525-83ac-2569482ce4ce)

**Comment by djc** [comment]
flamegraph just orchestrates a performance recording tool -- I'm guessing it would be `perf` on WSL? -- and pass the output to the inferno crate. In this case, it looks like flamegraph itself did everything it was asked to do, but one of these components did something surprising?

**Comment by albertsgarde** [comment]
Thanks. I'll try that.
