### ISSUE TITLE
Very long analysis due to slow addr2line calls

### ISSUE THREAD

**Issue by Mingun** [flamegraph-rs/flamegraph#294]
I try to use flamegraph to profile quick-xml benchmarks. I've run the following command in the quick-xml checkout:
```
cargo flamegraph --bench macrobenches -- --bench
```
`perf` collected over 8GB of raw data and analysis going more than a hour already. flamegraph runs `perf script` which runs `addr2line` many times, about 2-3 invocations per second. It seems to me that such a simple task consumes absurd time to complete. Probably it is better to find more performant solutions to process `perf` data.

**Comment by djc** [comment]
Maybe have a look at #74 and #199? I think there was an issue with some versions of the `addr2line` script. You may also want to try `samply` as a `flamegraph` alternative.

**Comment by Mingun** [comment]
Ah, ok, yes, this indeed a duplicate of those issues -- I'm on Ubuntu 22.04 with kernel 5.15 where perf performance is not fixed yet.

**Comment by RalfJung** [comment]
I am on binutils 2.43 and kernel 6.11 (current Debian testing), and I am still hitting this -- it's now already been around 10 minutes since perf finished (the actual program run took 3s and gathered 3k samples), and it's still spawning thousands and thousands of addr2line processes. Is there some new problem here?

**Comment by RalfJung** [comment]
Interesting, when I finally killed `perf script` I saw this error on the terminal printed a few hundred times:
```
addr2line /home/r/.debug/.build-id/37/8f73d84f9d89f55dfc18a9ab84bce321cd9b09/elf: could not read first record
```
No idea if that could have something to do with the performance problem.

**Comment by RalfJung** [comment]
Turns out using gimli's `addr2line` fixes this. Magic.
