### ISSUE TITLE
Frequency option is hardly documented

### ISSUE THREAD

**Issue by svix-jplatte** [flamegraph-rs/flamegraph#307]
From the `--help` output, it's impossible to tell

- What kind of input format is accepted (apparently the input is a number in Hz)
- What the default value is (AFAIU this is determined by perf's default, which _appears to be_ 1000 Hz, on my system)

**Comment by djc** [comment]
I probably won't able to work on this, but happy to review a PR if you want to take a stab at better documenting this?
