### ISSUE TITLE
docs: README should mention MacOS support

### ISSUE THREAD

**Issue by nrc** [flamegraph-rs/flamegraph#31]
Whether flamegraph supports MacOS or not, the README should say so.

**Comment by mimoo** [comment]
it doesn't : (

**Comment by jonhoo** [comment]
It does support it using `dtrace`, though I don't know how standard that is on macOS?

**Comment by mimoo** [comment]
```
dtrace: system integrity protection is on, some features will not be available
dtrace: failed to initialize dtrace: DTrace requires additional privileges
failed to sample program
```

**Comment by davidrusu** [comment]
You'll need to disable SIP on your mac to have dtrace work.

Mentioning this in the readme would be nice, and maybe also with a link to how to disable it:

https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html#//apple_ref/doc/uid/TP40016462-CH5-SW1

> reboot into recovery mode and run `csrutil disable`

**Comment by benhannel** [comment]
I have system integrity protection off, and flamegraph still can't use dtrace:
```
bens-mbp-4:program bhannel$ csrutil status
System Integrity Protection status: disabled.
bens-mbp-4:program bhannel$ cargo flamegraph --bin=bench
warning: `panic` setting is ignored for `test` profile
    Finished release [optimized] target(s) in 0.02s

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true

dtrace: failed to initialize dtrace: DTrace requires additional privileges
failed to sample program
```

**Comment by bjorn3** [comment]
You need to use `sudo`.

**Comment by benhannel** [comment]
Thanks! I was trying `sudo su` and had issues but just `sudo cargo flamegraph --bin=bench` works.

**Comment by bjorn3** [comment]
You can also use `cargo flamegraph --sudo --bin=bench` to prevent any rustc invocations being performed as root.

**Comment by capnfabs** [comment]
As at 20 Feb, the above invocation should be `cargo flamegraph --root --bin=bench`, but I can confirm that it works ✨

**Comment by djc** [comment]
@rsqv would you like to submit a PR? I'd be happy to review it!

**Comment by mimoo** [comment]
the `--sudo` flag doesn't work anymore.
