### ISSUE TITLE
Can you place performance marks/waypoints in code that are visible in the output?

### ISSUE THREAD

**Issue by alshdavid** [flamegraph-rs/flamegraph#315]
I'm trying to identify what is happening between two points - is there a way/what is the best way to mark the start/end points in code such that they are visible on the flamechart?

**Comment by djc** [comment]
`flamegraph`/`cargo flamegraph` are mostly wrappers around `perf` (on Linux) and there is some support for dtrace on macOS. If you want, you can supply your own `perf` command invocation or render the flamegraph using the data supplied from a pre-run `perf` run. I'd look for generic advice on doing what you need with `perf` and working from there.
