### ISSUE TITLE
Partially missed stack trace

### ISSUE THREAD

**Issue by dima74** [flamegraph-rs/flamegraph#337]
Consider simple Rust program calculating fibonacci number:
```rust
fn main() {
    println!("{}", fibonacci(42));
}

fn fibonacci(n: u32) -> u32 {
    match n {
        0 => 0,
        1 => 1,
        _ => fibonacci(n - 1) + fibonacci(n - 2),
    }
}
```

Here is result of `cargo flamegraph`:

![image](https://github.com/user-attachments/assets/8ec0a986-da6f-492d-b2dc-54b445219a3b)

Approximately half of the `fibonacci` calls have correct stacktrace, however other half doesn't have stacktrace

**Comment by djc** [comment]
This is more due to the underlying profiling backend (`perf` if you're on Linux), not flamegraph itself. You might be able to increase the profiling frequency to capture a larger percentage of stack traces, at the expense of slower runtime.

**Comment by dima74** [comment]
I don't observe such behaviour when using `perf` directly with the same frequence as `cargo flamegraph` uses by default. 

With `perf`:
```
cargo build --example fib && perf record -F 997 -g -- ./target/debug/examples/fib && perf script | stackcollapse-perf.pl | flamegraph.pl >flamegraph1.svg
```
![image](https://github.com/user-attachments/assets/53db9d34-a00f-4abd-a8a2-1f0b761bf59f)

With `cargo flamegraph`:
```
cargo build --example fib && flamegraph -o flamegraph2.svg -- ./target/debug/examples/fib
```

![image](https://github.com/user-attachments/assets/6368316d-8dc5-40b9-a5e4-4ab0525c27df)

---

When using `cargo flamegraph`, there are 9% `[unknown]` samples, when using `perf` directly there are no `[unknown]` samples

**Comment by mstange** [comment]
The difference is probably the passing of `-g` rather than `--call-graph dwarf`. So maybe the issue is caused by perf's dwarf unwinding.

**Comment by dima74** [comment]
Maybe add info to the README that `cargo flamegraph` uses `--call-graph dwarf` and example how to use `-g` instead

**Comment by djc** [comment]
Happy to review a PR.
