### ISSUE TITLE
Running my application under flamegraph makes it 32% faster

### ISSUE THREAD

**Issue by meltyness** [flamegraph-rs/flamegraph#339]
My application, `ratchet`, has a critical path that I've set up some test points to get a runtime over.

When I run it using flamegraph (under WSL/Ubuntu), the average runtime drops by 30%

The system doesn't have very many dependencies, but I'm not sure how to approach this... what is `flamegraph` doing right? how?

...huh?

```
$ cargo rr -- --add-insecure-test-credential-do-not-use --ignore-i18n
    Finished `release` profile [optimized] target(s) in 0.32s
     Running `target/release/ratchet --add-insecure-test-credential-do-not-use --ignore-i18n`
^CRatchet Debug: Average processing time over 58816 runs: 32.003µs
```

```
$ flamegraph -- cargo rr -- --add-insecure-test-credential-do-not-use --ignore-i18n
WARNING: Kernel address maps (/proc/{kallsyms,modules}) are restricted,
check /proc/sys/kernel/kptr_restrict and /proc/sys/kernel/perf_event_paranoid.

Samples in kernel functions may not be resolved if a suitable vmlinux
file is not found in the buildid cache or in the vmlinux path.

Samples in kernel modules won't be resolved at all.

If some relocation was applied (e.g. kexec) symbols may be misresolved
even with a suitable vmlinux or kallsyms file.

Couldn't record kernel reference relocation symbol
Symbol resolution may be skewed if relocation was used (e.g. kexec).
Check /proc/kallsyms permission or run as root.
    Finished `release` profile [optimized] target(s) in 0.38s
     Running `target/release/ratchet --add-insecure-test-credential-do-not-use --ignore-i18n`
^CRatchet Debug: Average processing time over 55167 runs: 20.989µs
[ perf record: Woken up 224 times to write data ]
[ perf record: Captured and wrote 56.727 MB perf.data (3557 samples) ]
^Cwriting flamegraph to "flamegraph.svg"
```

~~This could be a product of the warning listed, but I'm not sure.~~

## Tried so far, didn't change the issue
 - I adjusted one of the knobs mentioned, the warning has vanished, but the performance is still 30% better.
 - Retarget to musl

**Comment by meltyness** [comment]
https://github.com/meltyness/ratchet/tree/devel/timing-diagnostic

there's a branch here with the diagnostic that appears upon `ctrl+c` as well as a supporting script that creates lots of tests by running `perl hammerit.pl` 

The only outside dependency is on Ubuntu or Debian to grab `apt install libauthen-tacacsplus-perl` from the official repos.

**Comment by djc** [comment]
I don't think it's got anything to do with flamegraph itself. Try running it under perf directly? For a wild guess, maybe the profiling slowdown is reducing lock contention such that it ends up faster?

**Comment by meltyness** [comment]
Yeah I'm starting to realize I've misrouted this but I appreciate the help.

**Comment by meltyness** [comment]
@djc in case you were curious, I did find a way to achieve the same benefit without `perf` ...

In the case of my application, using the `busy_poll` and `busy_read` knobs produces a similar benefit. I have no idea why or if I could ever repeat the process I used to discover that fact but... ✨🧙‍♂️🐇🎩
