### ISSUE TITLE
Cannot pass --bench argument to the executable

### ISSUE THREAD

**Issue by stjepang** [flamegraph-rs/flamegraph#34]
I want to benchmark `foo --bench` like this:

```
cargo flamegraph -e foo --bench
```

Unfortunately, `cargo-flamegraph` is trying to interpret the `--bench` argument rather than passing it to `foo`:

```
error: Found argument '--bench' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-flamegraph flamegraph --exec <exec>

For more information try --help
```

I tried `cargo flamegraph -e foo -- --bench` and `cargo flamegraph -e -- foo --bench` but no luck :(

**Comment by djc** [comment]
This might be considered a variant of #1.

**Comment by jonas-schievink** [comment]
This should work just fine now!

**Comment by jonas-schievink** [comment]
Closing as fixed.
