### ISSUE TITLE
High Amount of lost Samples and Weird Flamegraph

### ISSUE THREAD

**Issue by C0D3-M4513R** [flamegraph-rs/flamegraph#349]
When running my project with cargo flamegraph I started getting weird results in my latest iteration of my program.

After my Program has finished (after ~8-9min) I get this:
```
[ perf record: Woken up 34103 times to write data ]
Warning:
Processed 793565 events and lost 6526 chunks!

Check IO/CPU overload!

Warning:
Processed 714213 samples and lost 15,96%!

[ perf record: Captured and wrote 9524,038 MB perf.data (600229 samples) ]
writing flamegraph to "flamegraph.svg"
```

I've never seen such a high percentage of lost samples, and wanted to ask if there is a way to reduce it, by e.g. suspending all threads whilst sample data is being written.

The Flamegraph also splits certain call stacks in multiple locations:
![image](https://github.com/user-attachments/assets/f0d41586-819f-4a89-80a3-e20e75510ce8)
In both situations, the higher up call stack is the correct one.

I don't know if there is more fragmentation in the Flamegraph. These were just the calls that I could Identify on a quick glance. The code and testing data for this project are currently private.

If you have some ideas on how to maybe get more accurate results, please lmk.

**Comment by djc** [comment]
flamegraph is just a (pretty thin) wrapper around `perf` (on Linux), so for this issue you should probably investigate the way `perf` is invoked underneath.

You could also see if you get better results when using samply.

**Comment by C0D3-M4513R** [comment]
Thanks for the pointer to samply.
