### ISSUE TITLE
WINDOWS  Only shows syscall in flamegraph while using Dtrace 

### ISSUE THREAD

**Issue by meipeter** [flamegraph-rs/flamegraph#358]
Using dtrace 
![图片](https://github.com/user-attachments/assets/bf16a628-118e-4d6f-b551-b67c118288bc)
;Ps _badapplemoon_ is the program name

Using bliond

![图片](https://github.com/user-attachments/assets/a82f1cf0-36b0-4f06-845b-ceb411908c8a)

**Comment by djc** [comment]
So use the blondie backend?

**Comment by meipeter** [comment]
#405
