### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by k0nserv** [flamegraph-rs/flamegraph#61]
Hey 👋,

I wanted to use `flamegraph` for some tests which seems to have been added in #27 however I think the most recent release was cut before this PR was merged.

Could you release a new verison please?

**Comment by jonas-schievink** [comment]
Hi! I'm hoping that we'll manage to publish a new release in the coming weeks.

For now, you can use `cargo install --git https://github.com/ferrous-systems/flamegraph.git` to install the git version.

**Comment by k0nserv** [comment]
Thanks, I didn't know it was possible to install from git like taht
