### ISSUE TITLE
Feature request: Specifying path to `perf` through environment

### ISSUE THREAD

**Issue by oxalica** [flamegraph-rs/flamegraph#63]
It seems the command `perf` (also, `dtrace`) is hard-coded and should be contained in `PATH`.
If `perf` is installed anywhere else, we need to modify `PATH` before running it, which is not a good way and may break other programs.

Related: https://github.com/NixOS/nixpkgs/pull/76313

**Comment by jonas-schievink** [comment]
Perhaps we should respect `PERF` and `DTRACE` environment variables if they're set?

**Comment by djc** [comment]
Looks like this has been implemented in #92.
