### ISSUE TITLE
`cargo install` error

### ISSUE THREAD

**Issue by TheMayoras** [flamegraph-rs/flamegraph#67]
When trying to install via Cargo, I get the following error:
```
error[E0425]: cannot find value `exit_status` in this scope
   --> C:\Users\Omen\.cargo\registry\src\github.com-1ecc6299db9ec823\flamegraph-0.1.13\src\lib.rs:134:6
    |
134 |     !exit_status.success()
    |      ^^^^^^^^^^^ not found in this scope

error: aborting due to previous error
```

I am on Windows 10, I tried installing using CMD.exe and Git Bash.  I also tried with and without admin privileges.  Any help is appreciated!

**Comment by jonas-schievink** [comment]
Thanks, this is fixed on master since a while already, so closing. I'll prepare a new release.
