### ISSUE TITLE
Moving the ownership of crate cargo-flamegraph

### ISSUE THREAD

**Issue by golddranks** [flamegraph-rs/flamegraph#69]
Hi, I'm the current owner of crate `cargo-flamegraph`.

A few years back, I developed a flamegraph tool for cargo in my work. I reserved the crate `cargo-flamegraph` for me to be eventually able to publish my work. However, publishing OSS in enterprise environments isn't always easy, and I didn't have to energy to drive that home.

I think the current flamegraph tool in this repo exceeds my work in functionality and code quality, and apparently it's confusing for the users that there exists an empty crate `cargo-flamegraph`, a common pattern for cargo related tools. So it would be better for you have the crate. What do you think?

(@spacejam actually sent me an email around a year back about a transfer, but at that time I wasn't sure whether I was going to give up with publishing. Now I think that it's better for you have the crate.)

**Comment by jonas-schievink** [comment]
Sounds like a good idea! Feel free to transfer it to me, then I'll add the team as owners.

We'll have to figure out if/how to publish both crates at once for the next release (or whether to maybe deprecate the `flamegraph` crate).

**Comment by golddranks** [comment]
@jonas-schievink I sent you an ownership invitation in crates.io. Did you get it?

**Comment by jonas-schievink** [comment]
Yup, thanks!

**Comment by spacejam** [comment]
@golddranks thank you very much, that is quite generous of you :]
