### ISSUE TITLE
Can not pass parameters to dtrace

### ISSUE THREAD

**Issue by JordiPolo** [flamegraph-rs/flamegraph#70]
I need to pass parameters to my binary,
I've tried
```
sudo cargo flamegraph -- ./target/release/minos -f ./3minirefparams.yaml
```
and
```
sudo flamegraph -- ./target/release/minos -f ./3minirefparams.yaml
```
and
```
sudo flamegraph ./target/release/minos -f ./3minirefparams.yaml
```

All of these would complain with
dtrace: invalid probe specifier ./3minirefparams.yaml: syntax error near "minirefparams"

or similar error. It does not seem to like any parameter

Trying this on macos with dtrace backend

**Comment by ssundarr3** [comment]
If the command and args are wrapped in quotes, it seems to work.

i.e. if you do `sudo flamegraph "./target/release/minos -f ./3minirefparams.yaml"` I think it should work.
