### ISSUE TITLE
Profiling with workspace projects

### ISSUE THREAD

**Issue by tekjar** [flamegraph-rs/flamegraph#71]
```
[profile.release]
debug = true
```

profile seems to be ignored from my workspace projects in the root `Cargo.toml`

```
Finished release [optimized + debuginfo] target(s) in 2m 28s

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true
```

**Comment by jonas-schievink** [comment]
We use Cargo's JSON output to determine this. Does it not contain the required info?

**Comment by JayAndCatchFire** [comment]
This happens to me as well.  The emitted binary does have debug symbols included.  In other words, the `profile.release` settings are being applied correctly.  However, flamegraph emits that warning regardless.

**Comment by TheDan64** [comment]
I am also seeing this warning despite having debuginfo enabled. However, I am running a regular Cargo project and not a workspace.

**Comment by jonas-schievink** [comment]
It would be great if someone here could test the fix in #77 on a workspace project

**Comment by necabo** [comment]
I tested it myself using the workspace example from the Rust book now. Looks good to me regarding the warning:
```
~/projects/add via 𝗥 v1.41.1
➜ ../flamegraph/target/release/cargo-flamegraph flamegraph --bin adder
    Finished release [optimized] target(s) in 0.00s

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true

Hello, world! 10 plus one is 11!
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.045 MB perf.data (5 samples) ]
writing flamegraph to "flamegraph.svg"

# Add debuginfo to release profile
~/projects/add via 𝗥 v1.41.1
➜ nvim Cargo.toml

~/projects/add via 𝗥 v1.41.1 took 16s
➜ ../flamegraph/target/release/cargo-flamegraph flamegraph --bin adder
   Compiling add-one v0.1.0 (/home/necabo/projects/add/add-one)
   Compiling adder v0.1.0 (/home/necabo/projects/add/adder)
    Finished release [optimized + debuginfo] target(s) in 0.20s
Hello, world! 10 plus one is 11!
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.046 MB perf.data (5 samples) ]
writing flamegraph to "flamegraph.svg"
```

For some reason however the generated flamegraph doesn't contain any function names. I'm not too familiar with workspaces so I'm not sure if I'm missing something here, the cargo output however leads me to believe it's not an issue with how the crates are built.

**Comment by jonas-schievink** [comment]
> For some reason however the generated flamegraph doesn't contain any function names.

That might just be because the program only runs very shortly. Benchmarking a real workload should not have that problem.

**Comment by JayAndCatchFire** [comment]
> > For some reason however the generated flamegraph doesn't contain any function names.
> 
> That might just be because the program only runs very shortly. Benchmarking a real workload should not have that problem.

I've found that increasing the sample frequency often helps in that situation.
