### ISSUE TITLE
flamegraph sometimes runs the wrong binary in `--test` mode

### ISSUE THREAD

**Issue by rcoh** [flamegraph-rs/flamegraph#79]
Command:
`cargo flamegraph --test fill_integ`

Binary that gets run (snooped via strace):
`rust-wasm/target/release/fill_integ-0d31b301ef6d061y`

contents of folder:
```
➜  rust-wasm git:(rust-wasm) ✗ ls -latr target/release/fill_integ-*
-rw-rw-r-- 1 russell russell      584 Mar 15 23:08 target/release/fill_integ-0d31b301ef6d0617.d
-rwxrwxr-x 3 russell russell 11542904 Mar 16 01:03 target/release/fill_integ-0d31b301ef6d0617
-rw-rw-r-- 1 russell russell      584 Mar 16 23:45 target/release/fill_integ-dc6d5509fba706c0.d
-rwxrwxr-x 2 russell russell 12489304 Mar 18 11:25 target/release/fill_integ-dc6d5509fba706c0
```

`-dc6....` is the new binary that should be run but flamegraph is runnin g `0d31b`.

Workaround is deleting the old binary.

**Comment by djc** [comment]
I think #141 has fixed this, so I'll close this issue. If you want to give it a shot (from Git main), that would be great. If there's still an issue, please feel free to reopen.
