### ISSUE TITLE
"perf.map" as stack info in SVG output

### ISSUE THREAD

**Issue by landaire** [flamegraph-rs/flamegraph#91]
When generating a flamegraph for my application on `Linux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux` I see the following in the output:

![image](https://user-images.githubusercontent.com/1313522/85457177-97fc5c00-b554-11ea-814f-c54b93c8816b.png)

Some of the data I expect is here, but these large slices have no relevant info and I'm missing functions which I know are definitely executed. From looking at the `inferno` code it looks like it may be expecting these files in `/tmp/perf-*.map` but no such files are present. Are there some additional steps I'm missing?

I installed flamegraph today using `cargo install flamegraph`, so it should be up-to-date.

**Comment by landaire** [comment]
Few things with this that I think I answered myself. The `perf-<NUM>.map` is actually the PID of the process and its children, but we do some weird stuff in this application that results in a rwx section being mapped at runtime. So those bits are actually this rwx section.

The second thing is that apparently the section of code I thought I should be seeing wasn't showing up in the flamegraph because it runs significantly faster than most other things, so when sampling occurs for my short-lived traces I'm in other places.

**Comment by bjorn3** [comment]
> The `perf-<NUM>.map` is actually the PID of the process and its children, but we do some weird stuff in this application that results in a rwx section being mapped at runtime.

https://lkml.org/lkml/2009/6/8/499

> This patch adds support for profiling JIT generated code to 'perf
> report'. A JIT compiler is required to generate a "/tmp/perf-$PID.map"
> symbols map that is parsed when looking and displaying symbols.

**Comment by bjorn3** [comment]
As an example how to write it: https://github.com/bytecodealliance/cranelift/pull/571/files

**Comment by landaire** [comment]
Thanks @bjorn3! That may prove to be useful.
