### ISSUE TITLE
Cannot run sub-crate binary in workspace

### ISSUE THREAD

**Issue by nicomem** [flamegraph-rs/flamegraph#93]
## Description
In a cargo workspace, I cannot select the binary of a sub-crate, even though it is recognized by flamegraph.

## Steps to reproduce
Create a new binary crate and another sub-crate inside the first:
```shell
cargo new --bin foo && cd foo
cargo new --bin bar
```

Add these lines to Cargo.toml of the "foo" crate:
```toml
[workspace]
members = [".", "bar"]
```

Then try to run flamegraph on both binaries:
```shell
cargo flamegraph --version
>>> cargo-flamegraph-flamegraph 0.3.0

# Find the different binaries of the crate and sub-crates
cargo flamegraph
>>> several possible targets found: ["foo", "bar"], please pass `--bin <binary>` or `--example <example>` to cargo flamegraph to choose one of them

# The root crate binary works
cargo flamegraph --bin foo

# Do not find the binary of the sub-crate
cargo flamegraph --bin bar
>>> error: no bin target named `bar`
>>> Did you mean `foo`?
```

I found out that running it inside the sub-crate works, but in my opinion it should directly work in the root crate or at least tell the user that it should run flamegraph in the sub-crate:
```shell
cd bar

# Still need to specify the binary
cargo flamegraph
>>> several possible targets found: ["foo", "bar"], please pass `--bin <binary>` or `--example <example>` to cargo flamegraph to choose one of them

# Now flamegraph can run the sub-crate
cargo flamegraph --bin bar

# But the other is now broken
cargo flamegraph --bin foo
>>> error: no bin target named `foo`
>>> Did you mean `bar`?
```

**Comment by onsails** [comment]
I also noticed that it can't run workspace member even if inside of member directory in case when root workspace is a lib, not a binary.
